### ISSUE TITLE
#3886 - Alternative Mate

### ISSUE THREAD

**Issue by mevans86** [denialromeo/3412-chess-problems#5]
The solution for puzzle #3886 is missing an alternative mate in three.

1 Rd8+ Nxd8 2 Nd6++ Kf8 3 Qe8# is properly set up. However, there is an alternative on move 2:

2 Nc7++ Kf8 3 Qe8# also works.

**Comment by denialromeo** [comment]
Thank you for playing!

Yes, alternative solutions for many of the problems are not present. Recognizing them could take a fair amount of work. More details below.

https://github.com/denialromeo/4462-chess-problems/issues/4

**Comment by mevans86** [comment]
D’oh, sorry for the trouble! I completely understand. Thanks so much for this resource—it is _so_ much easier than lugging the book around. 😁
